name: "[BKLog] Web"

defaults:
  run:
    working-directory: bklog

on:
  push:
    paths:
      - 'bklog/web/**'
  pull_request:
    paths:
      - 'bklog/web/**'
  schedule:
    - cron: "0 10 * * *"

jobs:
  run:
    runs-on: ubuntu-20.04
    env:
      OS: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.2.0
      with:
        node-version: 18.12.0
    - name: Run build web
      run: |
        cd web
        npm install --legacy-peer-deps
        npm run build
